// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNFfRMSZmD6xjqPOZl9pr3Qip6SzAwaGo',
    appId: '1:335546961425:web:c65e4975aaa4c994ecabb0',
    messagingSenderId: '335546961425',
    projectId: 'sadany-store-db63c',
    authDomain: 'sadany-store-db63c.firebaseapp.com',
    storageBucket: 'sadany-store-db63c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYTFnT0Dmc4dhRRcLE5K7L0UFMnc4jeHY',
    appId: '1:335546961425:android:556f8015beb66149ecabb0',
    messagingSenderId: '335546961425',
    projectId: 'sadany-store-db63c',
    storageBucket: 'sadany-store-db63c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSJtZJxWzRq8PufekOfnVcSFmqxT2npEE',
    appId: '1:335546961425:ios:eb75d5882708c6e8ecabb0',
    messagingSenderId: '335546961425',
    projectId: 'sadany-store-db63c',
    storageBucket: 'sadany-store-db63c.firebasestorage.app',
    iosBundleId: 'com.example.sadanyStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSJtZJxWzRq8PufekOfnVcSFmqxT2npEE',
    appId: '1:335546961425:ios:eb75d5882708c6e8ecabb0',
    messagingSenderId: '335546961425',
    projectId: 'sadany-store-db63c',
    storageBucket: 'sadany-store-db63c.firebasestorage.app',
    iosBundleId: 'com.example.sadanyStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNFfRMSZmD6xjqPOZl9pr3Qip6SzAwaGo',
    appId: '1:335546961425:web:304dabce7d6144d4ecabb0',
    messagingSenderId: '335546961425',
    projectId: 'sadany-store-db63c',
    authDomain: 'sadany-store-db63c.firebaseapp.com',
    storageBucket: 'sadany-store-db63c.firebasestorage.app',
  );
}
